name: Deploy Bot

on: push

jobs:
  Fast-FTP-Action:
    name: Fast FTP Action
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: SFTP Upload
      uses: Dylan700/sftp-upload-action@latest
      with:
        server: us1.odd.gay
        username: kuriel23.4e2d7236
        password: ${{secrets.FTP_PASSWORD}}
        port: 2022
        uploads: |
          ./ => ./
        ignore: |
          *.git
          */**/*git*
          ./.vscode
    - name: Pterodactyl-Restart
      uses: supercrafter100/Pterodactyl-Restart@v1.0
      with:
        PTE_PANEL_URL: 'https://panel.odd.gay'
        PTE_BEARER_TOKEN: ${{ secrets.PTE_BEARER_TOKEN }}
        PTE_PANEL_ID: '4e2d7236'